[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.97"
serde = {version="1.0.164", features = ["derive"]}
log = "0.4.19"
lz4_flex = "0.10.0"
byteorder = "1.4.3"
plist = "1.4.3"
regex = "1.8.4"
base64 = "0.21.2"
chrono = "0.4.26"

[dev-dependencies]
simplelog = "0.12.1"
csv = "1.2.2"
chrono = "0.4.26"
criterion = "0.5.1"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false