[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
serde_json = "1.0.105"
serde = {version="1.0.188", features = ["derive"]}
log = "0.4.20"
lz4_flex = "0.11.1"
byteorder = "1.4.3"
plist = "1.5.0"
regex = "1.9.5"
base64 = "0.21.3"
chrono = "0.4.30"

[dev-dependencies]
simplelog = "0.12.1"
csv = "1.2.2"
chrono = "0.4.30"
criterion = "0.5.1"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false