[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.0"
serde_json = "1.0.79"
serde = {version="1.0.136", features = ["derive"]}
log = "0.4.14"
lz4_flex = "0.9.2"
byteorder = "1.4.3"
plist = "1.3.1"
regex = "1.5.5"
base64 = "0.13.0"
chrono = "0.4.22"

[dev-dependencies]
simplelog = "0.12.0"
csv = "1.1.6"
chrono = "0.4.19"
criterion = "0.3.5"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false