[package]
name = "macos-unifiedlogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
serde_json = "1.0.89"
serde = {version="1.0.147", features = ["derive"]}
log = "0.4.17"
lz4_flex = "0.9.5"
byteorder = "1.4.3"
plist = "1.3.1"
regex = "1.7.0"
base64 = "0.13.1"
chrono = "0.4.23"

[dev-dependencies]
simplelog = "0.12.0"
csv = "1.1.6"
chrono = "0.4.23"
criterion = "0.4.0"

[[bench]]
name = "high_sierra_benchmark"
harness = false

[[bench]]
name = "big_sur_benchmark"
harness = false

[[bench]]
name = "monterey_benchmark"
harness = false