[package]
name = "unifiedlog_parser_json"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simplelog = "0.12.0"
serde_json = "1.0.79"
log = "0.4.14"
macos-unifiedlogs = {path = "../../"}